import fs from "fs";
import path from "path";

// Optional: Reset for testing or SSR
export function resetTwSafelist() {
  const outPath = path.resolve(__dirname, "../tw-safelist.ts");
  const safelistArray: Array<string> = [];
  const content = `// 🚨 This file is auto-generated by tailwind-tree\n\n` + `export const twSafelist = ${JSON.stringify(safelistArray, null, 2)};\n`;

  fs.writeFileSync(outPath, content, "utf8");
}
